from typing import Dict, Set


am2r_regions: Dict[str, Set[str]] = {
    "Menu": {"Main Caves"},
    "Main Caves": {"Guardian", "First Alpha", "Hydro Station", "Mines", "Industrial Complex Nest", "Lower Main Caves"
                   "GFS Thoth"},
    "Lower Main Caves": {"The Tower", "Underwater Distribution Center", "Deep Caves"},
    "GFS Thoth": {"Genesis"},
    "Genesis": set(),
    "Guardian": {"After Guardian"},
    "After Guardian": {"Golden Temple", "Golden Temple Nest"},
    "Golden Temple": set(),
    "Golden Temple Nest": set(),
    "First Alpha": set(),
    "Hydro Station": {"Hydro Nest", "The Tower", "The Lab", "Arachnus", "Inner Hydro Station"},
    "Hydro Nest": set(),
    "Arachnus": set(),
    "Inner Hydro Station": set(),
    "Industrial Complex Nest": {"Pre Industrial Complex"},
    "Pre Industrial Complex": {"Complex Sand", "Torizo Ascended"},
    "Complex Sand": {"Industrial Complex"}, # added sand region because of the new launchers option since beam only wont work to leave
    "Torizo Ascended": set(),
    "Industrial Complex": set(),
    "Mines": set(),
    "The Tower": {"Tester Lower", "Tester Upper", "Geothermal"},
    "Tester Lower": {"Tester"},
    "Tester Upper": {"Tester"},
    "Tester": set(),
    "Geothermal": set(),
    "Underwater Distribution Center": {"EMP", "Serris", "Underwater Distro Connection"},
    "EMP": {"Post EMP"},
    "Post EMP": {"Pipe Hell BL"},
    "Pipe Hell BL": {"Pipe Hell BR", "Pipe Hell L"},
    "Pipe Hell BR": {"Pipe Hell L", "Pipe Hell R"},
    "Pipe Hell L": {"Pipe Hell R", "Fast Travel"},
    "Pipe Hell R": {"Screw Attack", "Underwater Distro Connection"},
    "Serris": {"Ice Beam"},
    "Ice Beam": set(),
    "Underwater Distro Connection": {},
    "Fast Travel": {"Golden Temple", "Complex Sand", "The Tower", "Gravity", "Underwater Distribution Center"},
    "Gravity": {"Pipe Hell Outside"},
    "Pipe Hell Outside": {"Pipe Hell R"},
    "Screw Attack": set(),
    "Deep Caves": {"Omega Nest"},
    "Omega Nest": {"The Lab"},
    "The Lab": {"Research Station"},
    "Research Station": set()
}
# todo: Have someone other than me verify this @(V)ariable
